# Generated by Django 3.1 on 2022-11-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mofified_date',
            new_name='modified_date',
        ),
    ]
